branch-defaults:
  master:
    environment: null
environment-defaults:
  go-demo-v1:
    branch: null
    repository: null
global:
  application_name: go-demo
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Preconfigured Docker
    - Go 1.4 running on 64bit Debian/2.8.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
